services:
  jjaniszewski.weatherapp.publicapi:
    image: jjaniszewski.weatherapp.publicapi
    build:
      context: .
      dockerfile: JJaniszewski.WeatherApp.PublicApi/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
